#!/bin/csh
# tr -d '\r' < loop1 > loop
# bash loop >& out.csv

for t in 1024 4096 16384 65536 262144 1048576 2097152 4194304
do
    for b in 8 32 128
    do
        # g++ -DNUMTRIALS=$t -DBLOCKSIZE=$b -o3 main.cpp -o main -lm -fopenmp
        /usr/local/apps/cuda/cuda-10.1/bin/nvcc -DNUMTRIALS=$t -DBLOCKSIZE=$b -o main  main.cu
        ./main
    done
done