#!/bin/bash
# tr -d '\r' < loop > looop
# bash looop

# for ls in 8 16 32 64 128 256 512
#   do
#     for gs in 1 2 4 8 16 32 64 128 256
#     do
#       g++ -DNMB=$gs -DLOCAL_SIZE=$ls -w -o first first.cpp /usr/local/apps/cuda/cuda-10.1/lib64/libOpenCL.so.1.1 -lm -fopenmp
#       ./first &>> out1.csv

#       g++ -DNMB=$gs -DLOCAL_SIZE=$ls -w -o second second.cpp /usr/local/apps/cuda/cuda-10.1/lib64/libOpenCL.so.1.1 -lm -fopenmp
#       ./second &>> out2.csv
#     done
# done

for ls in 32 64 128 256
  do
    for gs in 1 2 4 8 16 32 64 128 256 512 1024 2048
    do
      g++ -DNMB=$gs -DLOCAL_SIZE=$ls -w -o third third.cpp /usr/local/apps/cuda/cuda-10.1/lib64/libOpenCL.so.1.1 -lm -fopenmp
      ./third &>> out3.csv
    done
done