#!/bin/csh

# SBATCH -J project7b
# SBATCH -A cs475-575
# SBATCH -p class
# SBATCH -N 8 #number of nodes
# SBATCH -n 8 #number of tasks
# SBATCH --constraint=ib
# SBATCH -o proj7b.out
# SBATCH -e proj7b.err
# SBATCH --mail-type=BEGIN,END,FAIL
# SBATCH --mail-user=protzela@oregonstate.edu

module load openmpi
mpic++ main.cpp -o main -lm

for n in 1 2 4 8
do
    mpiexec -mca btl self,tcp -np $n main >> out.csv
done